# Generated by Django 5.1.7 on 2025-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_sale_fund_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('SIP', 'SIP'), ('LUMP', 'Lumpsum'), ('HI', 'Health Insurance'), ('TI', 'Term Insurance'), ('PMS', 'PMS'), ('AIF', 'AIF'), ('WILL', 'Will'), ('GI', 'General Insurance')], max_length=10),
        ),
    ]
