# Generated by Django 5.1.7 on 2025-09-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_sale_relationship_manager'),
    ]

    operations = [
    ]
