# Generated by Django 5.1.7 on 2025-09-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_backfill_sales_rm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='relationship_manager',
        ),
    ]
