# Generated by Django 5.1.7 on 2025-09-29 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_sale_relationship_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_history', to='crm.client')),
                ('relationship_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client RM History',
                'verbose_name_plural': 'Client RM Histories',
                'ordering': ['client', 'start_date'],
            },
        ),
    ]
