# Generated by Django 5.1.7 on 2025-10-04 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_clientrmhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('missed', 'Missed')], default='outgoing', max_length=20)),
                ('call_status', models.CharField(choices=[('connected', 'Connected'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], max_length=20)),
                ('call_purpose', models.CharField(choices=[('follow_up', 'Follow Up'), ('new_business', 'New Business'), ('service_request', 'Service Request'), ('complaint', 'Complaint'), ('information', 'Information'), ('portfolio_review', 'Portfolio Review'), ('other', 'Other')], default='follow_up', max_length=50)),
                ('call_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('phone_number', models.CharField(help_text='Phone number used for the call', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Call conversation notes')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('connection_time_seconds', models.IntegerField(blank=True, help_text='Time taken to connect in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.client')),
                ('relationship_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_start_time'],
            },
        ),
    ]
