# Generated by Django 5.1.7 on 2025-10-17 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDevelopmentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bdm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='sourced_by',
            field=models.ForeignKey(blank=True, help_text='BDM who sourced the client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_clients', to='crm.businessdevelopmentmanager'),
        ),
        migrations.AddField(
            model_name='lead',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_generated', to='crm.businessdevelopmentmanager'),
        ),
        migrations.AddField(
            model_name='sale',
            name='bdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.businessdevelopmentmanager'),
        ),
    ]
