# Generated by Django 5.1.7 on 2025-10-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_lead_client_email_lead_client_name_lead_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.client'),
        ),
    ]
