# Generated by Django 5.1.7 on 2025-10-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_lead_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='client_email',
            new_name='temp_client_email',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='client_name',
            new_name='temp_client_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='temp_client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.client'),
        ),
    ]
