# Generated by Django 5.1.7 on 2025-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0021_lead_relationship_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="product",
            field=models.CharField(
                choices=[
                    ("SIP", "SIP"),
                    ("LUMP", "Lumpsum"),
                    ("HI", "Health Insurance"),
                    ("TI", "Term Insurance"),
                    ("PMS", "PMS"),
                    ("AIF", "AIF"),
                    ("WILL", "Will"),
                    ("GI", "General Insurance"),
                    ("SIF", "Specialised Investment Funds"),
                ],
                max_length=10,
            ),
        ),
    ]
