# Generated by Django 5.1.7 on 2026-01-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0023_appraisalperiod_appraisalquestion_appraisalreview_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appraisalperiod",
            options={"ordering": ["-year", "-start_date"]},
        ),
        migrations.AddField(
            model_name="appraisalperiod",
            name="year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="employeeassignment",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("RM", "Relationship Manager"),
                    ("BDM", "Business Development Manager"),
                    ("MANAGER", "Manager"),
                    ("HR", "HR"),
                ],
                default="RM",
                max_length=10,
            ),
        ),
    ]
